# Generated by Django 3.2.15 on 2022-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0004_dishes_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(max_length=30),
        ),
    ]
