# Generated by Django 3.2.15 on 2022-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
