# Generated by Django 3.2.15 on 2022-09-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0007_auto_20220920_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('orderstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dispatch_mode',
            field=models.BooleanField(default=False),
        ),
    ]
