# Generated by Django 3.2.15 on 2022-09-24 23:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0008_auto_20220924_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=jsonfield.fields.JSONField(),
        ),
    ]
