# Generated by Django 3.2.12 on 2022-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0009_alter_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderstatus',
            new_name='orderproccesing',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordercomplete',
            field=models.BooleanField(default=False),
        ),
    ]
