# Generated by Django 3.2.12 on 2022-09-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangonative', '0010_auto_20220926_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order',
            field=models.JSONField(),
        ),
    ]
